#!/bin/bash
# bash is required because we need bash's printf to guarantee a cross-platform
# timestamp format.

set -e
set -x

if [ -z $ANDROID_HOME ]; then
    if [ -e ~/.android/bashrc ]; then
        . ~/.android/bashrc
    else
        echo "ANDROID_HOME must be set!"
        exit
    fi
fi

# standardize timezone to reduce build differences
export TZ=UTC

git reset --hard
git clean -fdx

cd trustedintents
./setup-ant

ant release-all

jarname=trustedintents-$(git describe)
rm -f ${jarname}*.asc

# standardize timestamps in ZIP headers
if which strip-nondeterminism > /dev/null; then
    for f in ${jarname}*.jar; do
	strip-nondeterminism -t jar -T $(git log -n1 --format=format:%at) $f
    done
fi

for f in ${jarname}*.jar; do
    sha256sum $f
done

if which gpg > /dev/null; then
    if [ -z "`gpg --list-secret-keys`" ]; then
        echo "No GPG secret keys found, not signing APK"
    else
        for f in ${jarname}*.*; do
            gpg --armor --detach-sign $f
        done
    fi
else
    echo "gpg not found, not signing APK"
fi
