#!/bin/sh

set -e
set -x

if ! which android > /dev/null; then
    if [ -z $ANDROID_HOME ]; then
        if [ -e ~/.android/bashrc ]; then
            . ~/.android/bashrc
        else
            echo "'android' not found, ANDROID_HOME must be set!"
            exit
        fi
    else
        export PATH="${ANDROID_HOME}/tools:$PATH"
    fi
fi

# fetch target from project.properties
eval `grep '^target=' project.properties`

CURDIR=`pwd`

android update lib-project --path ${CURDIR} --target $target
android update test-project --path ${CURDIR}/test --main ${CURDIR}
